### ISSUE TITLE
Guidance on implementing `KeyboardLayout`

### ISSUE THREAD

**Issue by SPuntte** [rust-embedded-community/pc-keyboard#36]
Hi,

thank you for maintaining this crate! :pray: 

I'm following along Philipp Oppermann's `blog_os` and implementing my local layout(s), primarily the [Finnish-Swedish QWERTY](https://en.wikipedia.org/wiki/QWERTY#Finnish%E2%80%93Swedish) and possibly the newer [Finnish multilingual](https://jkorpela.fi/sfs5966.html) one.

As I don't know the history or use cases of this crate, and to avoid creating more mess than necessary – should I create a PR for upstreaming my changes at some point, I'd like to hear your opinions on how to add new implementations for `KeyboardLayout`.

Currently, `layouts::Us104Key` seems to act as a "root layout" (probably because it was the first to be implemented?) with most others falling back on it via
```Rust
// impl KeyboardLayout for X
fn map_keycode(
    &self,
    keycode: KeyCode,
    modifiers: &Modifiers,
    handle_ctrl: HandleControl,
) -> DecodedKey {
    // ...
    match keycode {
        // ...
        e => {
            let us = super::Us104Key;
            us.map_keycode(e, modifiers, handle_ctrl)
        }
    }
}
```
Then again, at least [`De105Key`](/rust-embedded-community/pc-keyboard/blob/b1f55382064ef8796e3cc7670d2c63bcdcc7ae90/src/layouts/de105.rs#L113) and [`No105Key`](/rust-embedded-community/pc-keyboard/blob/b1f55382064ef8796e3cc7670d2c63bcdcc7ae90/src/layouts/no105.rs#L158) duplicate certain `KeyCode` mappings (`Escape`, `Backspace`, `Return`, etc.) that already exist in `Us104Key`.

For me, this immediately raises at least the following questions:

1. In which cases is it appropriate to fall back on the `Us104Key` (or any other) layout?
2. Does it make sense to create longer (with more than 2 layouts) layout chains? For example, since the [ISO layouts used in the Nordics](https://typingdonewell.com/blog/what-is-a-nordic-layout-the-list-of-all-nordic-layouts-with-explanation/) are very similar, I could reuse most of the number key mappings of `No105Key` for my `FiSe105Key`.

**EDIT:**
Also, related to my number 1 above, how about writing something like this?
```Rust
// impl KeyboardLayout for X
fn map_keycode(
    &self,
    keycode: KeyCode,
    modifiers: &Modifiers,
    handle_ctrl: HandleControl,
) -> DecodedKey {
    // ...
    let fallback = super::Us104Key;
    match keycode {
        // ...
        KeyCode::NumpadPeriod => {
            if modifiers.numlock {
                DecodedKey::Unicode(',')
            } else {
                fallback.map_keycode(keycode, modifiers, handle_ctrl)
            }
        }
    }
}
```
**EDIT 2:**
Then again, for consistency, one ought to do the same in many other places, e.g. for unmodified `Key0`...`Key9`, which might be worse for readability?

**Comment by jonathanpallant** [comment]
> probably because it was the first to be implemented?

exactly right.

> In which cases is it appropriate to fall back on the Us104Key (or any other) layout?

I would say, whenever the majority of the keys are handled by the 'parent' variant. It didn't seem to make sense to duplicate the entire match for US and UK, and have to fix bugs in both, so UK started as a special case of UK.

> Then again, at least [De105Key](https://github.com/rust-embedded-community/pc-keyboard/blob/b1f55382064ef8796e3cc7670d2c63bcdcc7ae90/src/layouts/de105.rs#L113) and [No105Key](https://github.com/rust-embedded-community/pc-keyboard/blob/b1f55382064ef8796e3cc7670d2c63bcdcc7ae90/src/layouts/no105.rs#L158) duplicate certain KeyCode mappings

Yeah that's not ideal.

> Does it make sense to create longer (with more than 2 layouts) layout chains? 

Sure. I would prioritise code space over execution type for a piece of code that at most executes a couple of times per second.

## Thoughts

Maybe one solution is to produce text-format tables of scan-code-to-Unicode-value and run a pre-build pre-processor that converts all of those tables into an optimally packed tree of match statements.

**Comment by SPuntte** [comment]
Thanks for the swift reply :)

> I would say, whenever the majority of the keys are handled by the 'parent' variant. It didn't seem to make sense to duplicate the entire match for US and UK, and have to fix bugs in both, so UK started as a special case of US.

Agreed.
 
> Sure. I would prioritise *code space* over *execution type* for a piece of code that at most executes a couple of times per second.

Sorry, I'm not sure if I understood that correctly.. Did you mean that, keyboard code being relatively "cold", you'd prefer smaller binary size over faster execution?

> ## Thoughts
> -- pre-build pre-processor --

Yup, sounds intriguing, and something that could be a fruitful exercise in DSL and compiler design. Maybe something like [`kbd`](http://kbd-project.org/) could be considered – though dynamic and maybe a tad complex – a form of "prior art"?

Personally, I currently lack a realistic use for such a system. However, I could see the support for dead keys, commonly used on European layouts, being a natural driver for something like this.

**Comment by SPuntte** [comment]
Alright. I think I got what I was after so I'm going to close this. Cheers!
