### ISSUE TITLE
Feature Request: Open up the API to allow access to the internal Modifiers struct from Keyboard

### ISSUE THREAD

**Issue by iTitus** [rust-embedded-community/pc-keyboard#39]
It would be nice to query the Keyboard directly for the state of the CTRL or the SHIFT keys.

**Comment by thejpster** [comment]
Sounds reasonable. You probably wouldn't want to let users change those fields, but functions to read the state would be ok. Either one function per modifier, or a function that returns a struct with pub fields so you get it all in one go, atomically. Either would work.

Feel free to send a PR!
