### ISSUE TITLE
Backslash key fails to work on Us104Key layout

### ISSUE THREAD

**Issue by pjht** [rust-embedded-community/pc-keyboard#45]
The backslash key is non-functional when using the Us104Key keyboard layout. 
This seems to be due to a mapping error, as 0x5D is mapped to the Oem7 keycode,
but the US layout uses the Oem5 key for the backslash, and Oem7 doesn't do anything. Seems like commit [e032488](https://github.com/rust-embedded-community/pc-keyboard/commit/e0324883a84470c8bd2dd2559fe874e1886db5fc) broke it, changing from Oem7 to Oem5 for the backslash in Us104Key.

**Comment by thejpster** [comment]
Oh no. Sorry about that. I should probably buy a US PS/2 keyboard for testing.

**Comment by thejpster** [comment]
So I think that key IS oem5 but maybe I'm mapping the wrong scam code to it.

**Comment by thejpster** [comment]
Oh no. My reference site is putting the oem keys in different places depending on the keyboard layout. That's not helpful at all.

I'll need to write some more test cases and then standardise on the US specific position of the oem keys.
